<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\Metalpol.Complaints.Application\Metalpol.Complaints.Application.csproj" />
    <ProjectReference Include="..\Metalpol.Complaints.Infrastructure\Metalpol.Complaints.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
